const { body } = require('express-validator');

exports.validateBusinessCreation = [
  body('dateTime').optional().isISO8601().withMessage('Invalid date format'),
  body('referenceNo').optional().isString(),
  body('companyName').notEmpty().withMessage('Company name is required'),
  body('businessType').notEmpty().withMessage('Business type is required'),
  body('tradeLicenseNo').notEmpty().withMessage('Trade license number is required'),
  body('passportIdNo').notEmpty().withMessage('Passport ID is required'),
  body('registrationPurpose').notEmpty().withMessage('Registration purpose is required'),
  body('email').isEmail().withMessage('Invalid email format'),
  body('postalCode').notEmpty().withMessage('Postal code is required'),
  body('ownerFirstName').notEmpty().withMessage('Owner first name is required'),
  body('ownerMiddleName').notEmpty().withMessage('Owner middle name is required'),
  body('ownerLastName').notEmpty().withMessage('Owner last name is required'),
  body('residentialAddress').notEmpty().withMessage('Residential address is required'),
  body('ownerCountry').notEmpty().withMessage('Owner country is required'),
  body('ownerState').notEmpty().withMessage('Owner state is required'),
  body('ownerCity').optional().isString(),
  body('ownerPhoneNumber').notEmpty().withMessage('Owner phone number is required'),
  body('gender').notEmpty().withMessage('Gender is required'),
  body('companyNationality').notEmpty().withMessage('Company nationality is required'),
  body('companyState').notEmpty().withMessage('Company state is required'),
  body('completOfficeAddress').notEmpty().withMessage('Complete office address is required'),
  body('companyCity').optional().isString(),
  body('ownerAddress').notEmpty().withMessage('Owner address is required'),
  body('nationalityPhoneNumber').notEmpty().withMessage('Nationality phone number is required'),
  body('residentPostalCode').notEmpty().withMessage('Resident postal code is required'),
  body('TradeCopy').notEmpty().withMessage('Trade copy is required'),
  body('PassportIDCopy').notEmpty().withMessage('Passport ID copy is required'),
  body('RequestLetter').notEmpty().withMessage('Request letter is required'),
  body('termsAccepted').isBoolean().withMessage('Terms accepted must be a boolean value'),
  body('termsAccepted').equals('true').withMessage('Terms must be accepted'),
];
