const { body } = require('express-validator');

exports.validateInvestorCreation = [
  body('dateTime').optional().isISO8601().withMessage('Invalid date format'),
  body('referenceNo').notEmpty().withMessage('Reference number is required'),
  body('firstName').notEmpty().withMessage('First name is required'),
  body('middleName').optional().isString(),
  body('lastName').notEmpty().withMessage('Last name is required'),
  body('profession').notEmpty().withMessage('Profession is required'),
  body('investType').notEmpty().withMessage('Investment type is required'),
  body('investVol').notEmpty().withMessage('Investment volume is required'),
  body('investmentInt').optional().isString(),
  body('investmentStartDate').notEmpty().withMessage('Investment start date is required'),
  body('registrationPurpose').notEmpty().withMessage('Registration purpose is required'),
  body('nationality').notEmpty().withMessage('Nationality is required'),
  body('nationalityState').notEmpty().withMessage('Nationality state is required'),
  body('nationalityCity').optional().isString(),
  body('nationalityPhoneNumber').notEmpty().withMessage('Nationality phone number is required'),
  body('businessName').notEmpty().withMessage('Business name is required'),
  body('residentialCountry').notEmpty().withMessage('Residential country is required'),
  body('residentialState').notEmpty().withMessage('Residential state is required'),
  body('residentialCity').optional().isString(),
  body('personalPhoneNumber').notEmpty().withMessage('Personal phone number is required'),
  body('passportIdNo').notEmpty().withMessage('Passport ID number is required'),
  body('email').isEmail().withMessage('Invalid email format'),
  body('residentialAddress').notEmpty().withMessage('Residential address is required'),
  body('gender').notEmpty().withMessage('Gender is required'),
  body('nationalityAddress').notEmpty().withMessage('Nationality address is required'),
  body('PassportIDCopy').notEmpty().withMessage('Passport ID copy is required'),
  body('CurrentPicture').notEmpty().withMessage('Current picture is required'),
  body('termsAccepted').isBoolean().withMessage('Terms accepted must be a boolean value'),
  body('termsAccepted').equals('true').withMessage('Terms must be accepted'),
];
