const mongoose = require("mongoose");

const businessSchema = new mongoose.Schema({
  dateTime: { type: String, default: new Date().toISOString() },
  referenceNo: { type: String, required: true },
  companyName: { type: String, required: true },
  businessType: { type: String, required: true },
  tradeLicenseNo: { type: String, required: true },
  passportIdNo: { type: String, required: true },
  registrationPurpose: { type: String, required: true },
  email: { type: String, required: true, unique: true },
  postalCode: { type: String, required: true },
  ownerFirstName: { type: String, required: true },
  ownerMiddleName:{ type: String,},
  ownerLastName: { type: String, required: true },
  residentialAddress: { type: String, required: true },
  ownerCountry: { type: String, required: true },
  ownerState:{ type: String, required: true },
  ownerCity: String,
  ownerPhoneNumber: { type: String, required: true },
  gender: { type: String, required: true },
  companyNationality: { type: String, required: true },
  companyState: { type: String, required: true },
  completOfficeAddress: { type: String, required: true },
  companyCity: String,
  ownerAddress: { type: String, required: true },
  nationalityPhoneNumber: { type: String, required: true },
  residentPostalCode: { type: String, required: true },
  TradeCopy:{ type: String, required: true },
  PassportIDCopy: { type: String, required: true },
  RequestLetter: { type: String, required: true },
  termsAccepted: { type: Boolean, required: true },
}, { timestamps: true });

module.exports = mongoose.model("BusinessRegister", businessSchema);